### ISSUE TITLE
Cannot compile develop branch in android studio

### ISSUE THREAD

**Issue by strubul** [wordpress-mobile/WordPress-Android#678]
Hello there,
I get the following error in android studio during compilation:

```
:compileBetagroupJava/home/strubul/WordPress-Android/src/org/xmlrpc/android/ApiHelper.java:412: error: cannot find symbol
    public static class SyncMediaLibraryTask extends HelperAsyncTask<List<?>, Void, Integer> {
                                                                     ^
  symbol:   class List
  location: class ApiHelper
```

I just have forked and cloned the branch and followed the instructions in the handbook:

```
strubul@ubuntu:~/WordPress-Android$ git status
 On branch develop
nothing to commit (working directory clean)
```

Am I doing something wrong? Any help would be appreciated.

**Comment by PanderMusubi** [comment]
Latest build on f-droid is version 2.7.1 from 12 April 2014. Perhaps one of the people involved in that build could please revive and update that?
