### PR TITLE
Update Gradle for Android Studio 3.1

### PR DESCRIPTION
**Pull request by 0nko**
This PR updates the Gradle dependencies and configuration to make it work with Android Studio 3.1.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragment.java [hunk 1]
```diff
@@ -306,6 +307,7 @@ private void showEmptyView(@StringRes int titleResId) {
         showEmptyView(titleResId, 0, 0);
     }
 
+    @SuppressLint("ResourceType")
```
Comment (aforcier) [inline WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragment.java]: It looks like this lint error came from the `> 0` checks for the resource IDs. Could we update those to `!= 0` and do away with the lint suppression?

File: libs/login/WordPressLoginFlow/build.gradle [hunk 2]
```diff
@@ -4,7 +4,7 @@ buildscript {
         google()
     }
     dependencies {
-        classpath 'com.android.tools.build:gradle:3.0.1'
+        classpath 'com.android.tools.build:gradle:3.1.0'
```
Comment (aforcier) [inline libs/login/WordPressLoginFlow/build.gradle]: Could you also update the gradle wrapper to `4.4`, and `libs/login/.travis.yml` to use `android-27` and build tools `27.0.3` (not directly related to this PR)? I checked and this is all that's needed for this to build when we push to the subtree.

File: libs/utils/WordPressUtils/build.gradle [hunk 3]
```diff
@@ -4,8 +4,8 @@ buildscript {
         google()
     }
     dependencies {
-        classpath 'com.android.tools.build:gradle:3.0.1'
-        classpath 'com.novoda:bintray-release:0.5.0'
+        classpath 'com.android.tools.build:gradle:3.1.0'
```
Comment (aforcier) [inline libs/utils/WordPressUtils/build.gradle]: Same as for the login subtree, let's update the gradle wrapper to `4.4`, and `.travis.yml` to use `android-27` and build tools `27.0.3` here so this can build on its own.

**Comment by aforcier** [comment]
@0nko this is pretty weird, but I'm unable to build the app in this branch:

```
e: /Users/alex/AndroidstudioProjects/WordPress-Android/WordPress/src/main/java/org/wordpress/android/modules/WordPressGlideModule.java:24: error: cannot find symbol
@GlideModule
 ^
  symbol: class GlideModule
e: /Users/alex/AndroidstudioProjects/WordPress-Android/WordPress/src/main/java/org/wordpress/android/modules/WordPressGlideModule.java:25: error: dagger.internal.codegen.ComponentProcessor was unable to process this class because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code.
public class WordPressGlideModule extends AppGlideModule {
       ^
```

Are you seeing this too? I was able to fix this by updating the `WordPress/build.gradle` and the `libs/login/WordPressLoginFlow/build.gradle` glide deps to the latest (`4.6.1`).

**Comment by 0nko** [comment]
@aforcier Yes, I've been struggling with this all afternoon yesterday. It worked locally but was failing in Travis. I'm not sure what is going on. When I restarted the build a few times it worked eventually.

**Comment by 0nko** [comment]
@aforcier I've update the subtrees and addressed your comments. Let's see if this builds and if not I can try updating Glide...

**Comment by aforcier** [comment]
Seems to be building now but I'm still unable to build this at all locally without upgrading Glide. Do you still have problems with the build if you upgrade Glide locally?

**Comment by aforcier** [comment]
:shipit:
